### ISSUE TITLE
Сделать тулзу для обновления бд

### ISSUE THREAD

**Issue by gurovic** [parallel-p/pesto#14]

**Comment by gurovic** [comment]
Денис Кузнецов
Правильнее всего сделать так:
- завести в базе табличку "конфигурация", пока что с одним полем "версия схемы бд".
- сделать тулу "заапгрейдить схему", тула знает текущую версию в коде, и у неё определены функции "апгрейд с версии N на N+1". Собственно, она читает версию схемы из БД и последовательно накатывает апдейты.

**Comment by Andrey-Tkachev** [comment]
константа ACTUAL_SCHEMA_VERSION  в update_db.py - версия базы, используемая в коде 
функции для перехода с версии N на N + 1 описываются в scheme_update_funcs.py

**Comment by gurovic** [comment]
- после db_filename во всех других секциях называется database
- а тесты где?)
