### ISSUE TITLE
Падают тесты на informatics (test_load, test_update)

### ISSUE THREAD

**Issue by gurovic** [parallel-p/pesto#18]
test_update (dao_cases_test.DAOCasesTest)
Traceback (most recent call last):
  File "/home/gurovic/pesto/dao_cases_test.py", line 58, in test_update
    self.assertEqual(self.cursor.mock_calls, calls)
AssertionError: [call.execute('SELECT kek FROM Cases WHERE id = ?', 1),
 call.fetchone(),
 call.execute('UPDATE Cases SET io_hash = :io_hash WHERE id = :id', {'io_hash': 'io_hash3', 'id': 1}),
 call.execute('SELECT kek FROM Cases WHERE id = ?', 2),
 call.fetchone(),
 call.execute('UPDATE Cases SET io_hash = :io_hash WHERE id = :id', {'io_hash': 'io_hash2', 'id': 2})] != [call.execute('SELECT io_hash FROM Cases WHERE id = ?', 1), call.fetchone(), call.execute('UPDATE Cases SET io_hash = :io_hash WHERE id = :id', {'io_hash': 'io_hash3', 'id': 1}), call.execute('SELECT io_hash FROM Cases WHERE id = ?', 2), call.fetchone(), call.execute('UPDATE Cases SET io_hash = :io_hash WHERE id = :id', {'io_hash': 'io_hash2', 'id': 2})]

ERRORS:

test_load (dao_cases_test.DAOCasesTest)
Traceback (most recent call last):
  File "/home/gurovic/pesto/dao_cases_test.py", line 15, in test_load
    self.assertEqual(self.dao_cases.deep_load(row), "440fae04f9e3619de0b8e9319a6a5f4b")
  File "/home/gurovic/pesto/dao_cases.py", line 13, in deep_load
    return self.load(row)
  File "/usr/local/lib/python3.3/unittest/mock.py", line 846, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/local/lib/python3.3/unittest/mock.py", line 904, in _mock_call
    result = next(effect)
StopIteration

**Comment by kalinochkind** [comment]
Вроде что-то исправил, нужно протестировать

**Comment by gurovic** [comment]
Теперь не падают
