### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by JohnHook059** [parallel-p/pesto#25]
Кинуть все тесты в одну папку

**Comment by gurovic** [comment]
А зачем? Мы специально клали _test.py рядом с тестируемым файлом, чтобы работать было удобно.

**Comment by gurovic** [comment]
Ну ладно, так тоже ничего

**Comment by JohnHook059** [comment]
Я подумал, что так будет удобнее ориентироваться в нашем проекте. Если я ошибаюсь, то коммит можно откатить.
