### ISSUE TITLE
Автоматическое обновление базы данных при запуске tool

### ISSUE THREAD

**Issue by kalinochkind** [parallel-p/pesto#28]
Предлагать пользователю обновить базу, если она старой версии

**Comment by gurovic** [comment]
Не уверен. Например, у пользователя может не быть данных для обновления базы

**Comment by kalinochkind** [comment]
Тогда оставлять поля пустыми. Если модель данных меняется, е

**Comment by gurovic** [comment]
Но ведь реально данных почти ни у кого нет...

**Comment by kalinochkind** [comment]
Тогда в dao при загрузке из базы нужно рассматривать два случая, если колонка есть и если ее нет
