### ISSUE TITLE
Один tool для запуска всего

### ISSUE THREAD

**Issue by kalinochkind** [parallel-p/pesto#29]
Сейчас их уже пять, потом может стать еще больше. Пользователю будет удобнее, если все действия будут выполняться из одного места.

**Comment by gurovic** [comment]
Во-первых, пользователи разные - есть мы, есть внешние пользователи.
Во-вторых, есть операции, которые делать опасно, например, импортировать БД - и может лучше им быть в отдельной тулзе.
А вот объединить tool и case_... было бы можно, но они очень разные внутри, это не так легко.
